import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js tutor",
    template: "$s | codingman",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
      <header style={{backgroundColor:"lightblue", padding: "1rem",}}>
        <p>Header</p>
      </header>

      {children}

      <footer style={{backgroundColor:"ghostWhite", padding: "1rem",}}>
        <p>Footer</p>
      </footer>
      </body>
    </html>
  )
}
